name: Release UI-Tweaks

on:
  repository_dispatch:
  push:
    tags:
    - "UI-Tweaks-v[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  release:
    name: Release UI-Tweaks
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Verify commit
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/UI-Tweaks-v/}" >> $GITHUB_ENV

      - name: Set version in modinfo.json
        run: |
          jq --arg v "$VERSION" '.version = $v' resources/modinfo/bitzartuitweaks/modinfo.json > tmp.json && mv tmp.json resources/modinfo/bitzartuitweaks/modinfo.json

      - name: Build
        run: dotnet build UI-Tweaks.sln --configuration Release -p:Version="$VERSION"

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: |
          dotnet publish ./src/UI-Tweaks/UI-Tweaks.csproj -o ./release/${VERSION}/src
          mv ./release/${VERSION}/UI-Tweaks.zip ./release/${VERSION}/UI-Tweaks_v${VERSION}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 📺 UI-Tweaks v${{ env.VERSION }}
          generate_release_notes: true
          make_latest: true
          files: |
            release/${{ env.VERSION }}/UI-Tweaks_v${{ env.VERSION }}.zip